src/main/entities/chef.py

* Changinf chef variable name:
before: chef_ability
after: chef_skills

Fix : changing chef variable name

---

src/main/entities/inventory.py
src/main/entities/order.py
src/main/entities/order_detail.py
src/main/repositories/generic_repository.py
src/main/repositories/item_repository.py
src/main/repositories/product_repository.py

Trying to follow a pattern when naming properties

Renamed properties to be more consistent

---

lib/repositories/impl/ingredient_repository_impl.py
lib/repositories/impl/product_repository_impl.py
lib/repositories/ingredient_repository.py
lib/repositories/product_repository.py

Since it is potentially possible that we may use another mechanism to process and store data we should think about flexibility and scalability for these layers

Added impl layer for repositories

---

.gitignore
.idea/.gitignore
.idea/EA_RESTAURANT.iml
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
README.md
lib/repositories/impl/ingredient_repository_impl.py
tests/lib/repositories/impl/ingredient_repository_impl_test.py
tests/utils/fixtures/ingredient_fixture.py

* Added tests using `unittest` library for ingredient repository.
* Added ingredient fixture.

Added tests for ingredient repository

---

.pylintrc
README.md

- adding pylint url to readme file
- Adding R0903 to pylintrc -> Too few public methods

Fixing: linters observation

---

src/tests/api/controllers/ingredient_controller_integration_test.py

* Adding ingredient controller integration test

feature : Added ingredient controller integration test

---

src/lib/repositories/impl/product_repository_impl.py

* Adding the update method to the product repository impl that I had left behind

Feature: adding update method to product repository impl

---

src/lib/repositories/impl/product_repository_impl.py
src/tests/lib/repositories/impl/product_repository_impl_test.py
src/tests/utils/fixtures/product_fixture.py

* Adding product repository impl unit test

Feature: Adding product repository impl unit test

---

src/api/controllers/product_controller.py
src/tests/api/controllers/product_controller_test.py

* Adding product controller
* Adding product controller unit test

Feature: Adding product controller and unit test

---

src/tests/api/controllers/product_controller_integration_test.py

* Adding product controller integration test

Feature: product controller integration test

---

src/tests/api/controllers/inventory_ingredient_controller_integration_test.py

* Adding inventory ingredient controller integration test

Adding inventory ingredient controller integration test

---

src/api/controllers/inventory_controller.py
src/tests/api/controllers/inventory_controller_test.py

* Adding inventory controller
* Adding inventory controller unit test

Feature: inventory controller

---

src/tests/api/controllers/inventory_controller_integration_test.py

* Adding inventory controller integration test

Feature: inventory controller integration test

---

src/lib/repositories/impl/order_detail_repository_impl.py
src/lib/repositories/order_detail_repository.py
src/tests/lib/repositories/impl/order_detail_repository_impl_test.py
src/tests/utils/fixtures/order_detail_fixture.py

* Adding order detail repository
* Adding order detail repository impl test

Feature: Adding order detail repository and unit test

---

src/api/controllers/order_detail_controller.py
src/tests/api/controllers/order_detail_controller_test.py

* Adding order detail controller
* Adding order detail controller unit test

Feature : Adding order detail controller and unit test

---

src/tests/api/controllers/order_detail_controller_integration_test.py

* Adding order detail controller integration test

Feature : adding order detail controller integration test

---

src/lib/repositories/impl/order_repository_impl.py
src/lib/repositories/order_repository.py
src/tests/lib/repositories/impl/order_repository_impl_test.py
src/tests/utils/fixtures/order_fixture.py

* Adding order repository
* Adding order repository unit test

Feature: order repository

---

src/api/controllers/order_controller.py
src/tests/api/controllers/order_controller_test.py

* Adding order controller
* Addin order controller unit test

Feature: Adding order controller and unit test

---

src/tests/api/controllers/order_controller_integration_test.py

* Adding order controller integration test

Feature: order controller integration test

---

src/lib/repositories/chef_repository.py
src/lib/repositories/impl/chef_repository_impl.py
src/tests/lib/repositories/impl/chef_repository_impl_test.py
src/tests/utils/fixtures/chef_fixture.py

* Adding chef repository
* Adding chef repositoy impl unit test

Feature: Adding chef repository and unit test

---

src/api/controllers/chef_controller.py
src/tests/api/controllers/chef_controller_test.py

* Adding chef controller
* Adding chef controller unit test

Feature: Adding chef controller and unit test

---

src/api/controllers/__init__.py
src/core/decorators/singleton_decorator.py
src/core/ioc.py
src/lib/repositories/impl/__init__.py
src/tests/core/ioc_test.py

* Adding Ioc 
* Adding Ioc unit test
* Singleton decorator added, but will not be used for the moment.

Feature: ioc

---

src/lib/entities/inventory.py

* Changing date structure from list to dictionary. it is not efficient have to search all the list to get an specific ingredient inside the inventory.

Refactor: Changing inventory ingredients structure from list to dict

---

src/constants/cooking_type.py
src/lib/entities/ingredient.py
src/tests/utils/fixtures/ingredient_fixture.py
src/tests/utils/product_util_test.py
src/utils/product_util.py

Product preparation time function:
This function will be use to return the specific time that will take to prepare and ingredient as a part of a final product:
The step will be adding in the ingredient entity as a type. 
Example:
Cheese entity will have in the type: adding, it means that the cheese is an ingredient to add.
Example to prepare a peperoni pizza with the following ingredients:
Peperoni pizza:
preparing peperoni pizza:
ingredients:
pizza bread -> baking: 10
cheese -> adding: 2
sauce -> adding: 2
peperoni -> adding: 2
total time preparation: 10 + 2 + 2 + 2 = 16 minutes
bacon cheese burger:
preparing bacon cheese burger:
ingredients:
hamburger bread: roasting: 3
meat: frying: 5
cheese: adding: 2
bacon: adding: 2
vegetables: adding 2
total time preparation: 3 + 5 + 2 + 2 + 2 = 14 …

Feature: adding product preparation time util

---

src/core/order_manager.py
src/tests/core/order_manager_test.py
src/tests/utils/fixtures/order_fixture.py

*Changing the data that the queue stores from the whole order to just the order id.

Refactor: changing what queue stores from the whole order to just the order id

---

src/lib/entities/product.py
src/lib/entities/product_ingredient.py
src/lib/repositories/impl/product_ingredient_repository_impl.py
src/lib/repositories/product_ingredient_repository.py
src/tests/lib/repositories/impl/product_ingredient_repository_impl_test.py
src/tests/utils/fixtures/product_ingredient_fixture.py

* Adding product ingredient entity : this entity will be used to relate the product with the ingredient and it quantity, the quantity that the product need to be made.
* Adding product ingredient repository
* Adding product ingredient fixture
* Adding product ingredient repository test

Feature: product ingredient entity, repository and repository test

---

src/api/controllers/order_detail_product_controller.py
src/tests/api/controllers/order_detail_product_controller_integration_test.py
src/tests/api/controllers/order_detail_product_controller_test.py

* adding order detail product controller
* adding order detail product controller unit test
* adding order detail product controller integration test

Adding order detail product controller, unit and integration test

---

src/lib/entities/product.py
src/lib/repositories/impl/product_ingredient_repository_impl.py
src/lib/repositories/product_ingredient_repository.py
src/tests/lib/repositories/impl/product_ingredient_repository_impl_test.py
src/tests/utils/fixtures/product_fixture.py

* Adding method inside product_ingredient repository to get all the product_ingredient of a product by filter
the product_ingredients that the product.id matches with the product.id send by parameters.
* Adding repository unit test for get product ingredients of a product

feature: adding method to get the product ingredients of a product from repo

---

src/api/controllers/product_ingredient_controller.py
src/lib/entities/product.py
src/lib/repositories/impl/product_ingredient_repository_impl.py
src/lib/repositories/product_ingredient_repository.py
src/tests/api/controllers/product_ingredient_controller_integration_test.py
src/tests/api/controllers/product_ingredient_controller_test.py
src/tests/lib/repositories/impl/product_ingredient_repository_impl_test.py
src/tests/utils/fixtures/product_fixture.py

*Adding method to get product ingredients by product through controller , unit test and integration test

Feature: adding method to return product ingredients in controller

---

src/lib/entities/order_detail.py
src/lib/repositories/impl/order_detail_product_repository_impl.py
src/lib/repositories/order_detail_product_repository.py
src/tests/lib/repositories/impl/order_detail_product_repository_impl_test.py

* Adding method to get order products by order detail to repository
* Adding unit test for method in repository
This method will get all the order products relate with an order detail from the repository.

adding method to get order products by order_detail

---

src/api/controllers/order_detail_product_controller.py
src/tests/api/controllers/order_detail_product_controller_integration_test.py
src/tests/api/controllers/order_detail_product_controller_test.py

* Adding method to get order detail products by order detail to controller
* adding controller unit and integration test for this method

feature: adding method to get order detail products by order_detail controller

---

src/api/controllers/inventory_ingredient_controller.py
src/lib/entities/inventory.py
src/lib/repositories/impl/inventory_ingredient_repository_impl.py
src/lib/repositories/inventory_ingredient_repository.py
src/tests/api/controllers/inventory_ingredient_controller_integration_test.py
src/tests/api/controllers/inventory_ingredient_controller_test.py
src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py

* Adding method to get inventory ingredient by ingredient id in controller
* Adding unit and integration test of this method

Feature: method get ingredient inventory by ingredient id controller

---

src/lib/entities/inventory_ingredient.py
src/tests/utils/fixtures/inventory_ingredient_fixture.py

* Adding inventory to inventory ingredient entity

Refactor: Adding inventory to inventory ingredient entity

---

src/lib/entities/chef.py
src/lib/entities/ingredient.py
src/lib/entities/inventory.py
src/lib/entities/inventory_ingredient.py
src/lib/entities/order.py
src/lib/entities/order_detail.py
src/lib/entities/order_detail_product.py
src/lib/entities/product.py
src/lib/entities/product_ingredient.py

* Adding audit varibles to all the entities
* status
* create_date
* update_date
* create_by
* update_by
This varibles will be use to manage when an entity is create, update and who create/update it.

Feature: Adding audit varibles to all entities

---

src/core/ioc.py

* Adding order manager to ioc.

Feature: Adding order manager to ioc

---

src/lib/repositories/impl/inventory_ingredient_repository_impl.py
src/lib/repositories/inventory_ingredient_repository.py
src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py

* Adding method to validate ingredient availability
* Adding test for validate ingredient availability
This method will take two arguments(the **ingredient** to validate and the **quantity to use**) , with the **ingredient.id** the method filter inside the repository the **inventory_ingredient** that match with the **ingredient id**, after that it compare its **quantity** with the **quantity to use**, if **quantity** is higher that **quantity to use** the method return **True** otherwise return **False**.

Featute: Adding method to validate ingredient availability

---

src/api/controllers/inventory_ingredient_controller.py
src/tests/api/controllers/inventory_ingredient_controller_integration_test.py
src/tests/api/controllers/inventory_ingredient_controller_test.py

* Adding method to validate ingredient availability to controller
* Adding controller unit test for this method
* Addong controller integration test for this method

Feature: adding method to validate ingredient availability to controller

---

src/lib/entities/order_status_history.py
src/lib/repositories/impl/order_status_history_repository_impl.py
src/lib/repositories/order_status_history_repository.py
src/tests/lib/repositories/impl/order_status_history_repository_impl_test.py
src/tests/utils/fixtures/order_status_history_fixture.py

* Adding order status history entity
* Adding order status history repository
* Adding order status history repository test
* Adding order status history fixture
This entity will be use to develop a mechanism to manage the order status throght the different status that an order have and the time when the status change.

Feature: Adding order status history entity and repository

---

src/api/controllers/order_status_history_controller.py
src/tests/api/controllers/order_status_history_controller_integration_test.py
src/tests/api/controllers/order_status_history_controller_test.py

* Adding order status history controller
* Adding order status history controller unit test
* Adding order status history controller integration test

Feature: Adding order status history controller and test

---

src/api/controllers/__init__.py
src/core/ioc.py
src/lib/repositories/impl/__init__.py

* Adding order status history repository to ioc
* Adding order status history controller to ioc

Feature: Adding order status history repository and controller to ioc

---

src/core/ioc.py

* Refactoring imports at the Ioc to be more consistent.

Refactor : Refactoring imports to be more consistent

---

src/seed/initial_data.py

* Adding initial data to test the kitchen simulator process

Feature : Adding initial data to test kitchen simulator process

---

src/lib/entities/order_status_history.py
src/lib/repositories/impl/order_status_history_repository_impl.py
src/lib/repositories/order_status_history_repository.py
src/tests/lib/repositories/impl/order_status_history_repository_impl_test.py
src/tests/utils/fixtures/order_status_history_fixture.py

* Adding method to update order status history in repository
* Adding test for this method
* updating order status history: order to order_id

Feature: Adding method to update order status history

---

src/api/controllers/order_status_history_controller.py
src/tests/api/controllers/order_status_history_controller_integration_test.py
src/tests/api/controllers/order_status_history_controller_test.py

* Adding method to update order status history to controller
* Adding unit and integration controller test for this method
* Updating integration test for order status history controller: update order to order_id

adding method to update order status history to controller and test

---

src/api/controllers/chef_controller.py
src/tests/api/controllers/chef_controller_integration_test.py
src/tests/api/controllers/chef_controller_test.py

* Adding method to get available chef using controller
* Adding unit and integration test for this method using controller

Feature: Adding method to get available chef using controller

---

src/api/controllers/order_controller.py
src/tests/api/controllers/order_controller_integration_test.py
src/tests/api/controllers/order_controller_test.py

* Adding method to ger order ingredients by order id to controller
* Adding unit and integration test for this method.

Feature: Adding method to get order ingredients by order id to controller

---

src/tests/api/controllers/inventory_ingredient_controller_test.py
src/tests/api/controllers/order_controller_test.py
src/tests/api/controllers/order_detail_controller_test.py
src/tests/api/controllers/order_status_history_controller_test.py
src/tests/api/controllers/product_ingredient_controller_test.py

* Adding expected return value to controller unitest where it was necessary.

Adding expected return_value to controller unit test

---

src/seed/initial_data.py

* refactor - using object id instead whole object in the initial data

Refactor: using-id-instead-whole-object-in-the-initial-data

---

src/core/ioc.py
src/lib/entities/order.py
src/lib/repositories/impl/order_repository_impl.py
src/lib/repositories/order_repository.py
src/tests/lib/repositories/impl/order_repository_impl_test.py
src/tests/utils/fixtures/order_fixture.py
src/tests/utils/order_util_test.py
src/utils/order_util.py

* Adding method to get a map order valdiation.
This method will return a map that will contain order_id as key and True/False as a value, the result will depend if the order is valid or not.
with the order id it will get the quantity of product that could be made by product ingredients in the inventory

Feature: adding method to get a order validation map

---

src/api/controllers/order_controller.py
src/core/engine/processors/kitchen_simulator.py
src/core/order_manager.py
src/lib/repositories/impl/order_repository_impl.py
src/lib/repositories/order_repository.py
src/tests/core/engine/processors/kitchen_simulator_test.py

* Adding to kitchen simulator a method to assign valid orders to available chefs.
* Adding to kitchen simulator test a test for this method.

adding method to assign valid order to available chef

---

src/core/engine/processors/kitchen_simulator.py
src/lib/entities/ingredient.py
src/lib/entities/order.py
src/lib/entities/product_ingredient.py
src/tests/core/engine/processors/kitchen_simulator_test.py
src/tests/lib/repositories/impl/order_repository_impl_test.py
src/tests/utils/fixtures/product_ingredient_fixture.py
src/tests/utils/order_util_test.py
src/utils/order_util.py

* Adding method to calculate the order preparation time
* adding unit test for the order preparation time method
This method will get the product ingredients of an order by the order id and with the product ingredients will generate a list
with Cooking_type of the ingredient with this list and the chef skill the method will return the time that the chef will take to prepare the order.

Adding metho to get the order preparation time

---

src/lib/repositories/impl/order_repository_impl.py
src/lib/repositories/order_repository.py
src/tests/lib/repositories/impl/order_repository_impl_test.py

* Adding method to reduce the quantity of ingredients that an order need from the inventory
* Adding test for this method.

Adding method to reduce order ingredients from inventory

---

src/api/controllers/order_controller.py
src/tests/api/controllers/order_controller_integration_test.py
src/tests/api/controllers/order_controller_test.py

* Adding method reduce_order_ingredients_from_inventory to controller
* Adding unit and integration test for reduce_order_ingredients_from_inventory controller
* Adding unit and integration test for get_validated_orders_map controller

Feature: Adding order methods to controller and test

---

src/core/engine/processors/kitchen_simulator.py
src/tests/core/engine/processors/kitchen_simulator_test.py

* Adding method to reduce order ingredients from inventory to kitchen simulator in process order.

Feature: adding reduce order ingredients to kitchen simulator

---

src/core/order_manager.py
src/tests/core/engine/processors/kitchen_simulator_test.py
src/tests/core/order_manager_test.py

* Refactor: Changing order manager data structure from a queue to a priority queue.

refactor changing order manager data structure to a priority queue

---

src/core/engine/processors/kitchen_simulator.py
src/lib/entities/order.py
src/tests/core/engine/processors/kitchen_simulator_integration_test.py
src/tests/core/engine/processors/kitchen_simulator_test.py
src/utils/time_util.py

* Adding method to check for orders complete
* Adding unit and integration test for this method
This method will take the order in turn from in process queue and will ask if the time.now is higher than the time when the order status chance to in process + order estimated time if the condition is true means that the passed the necessary time for the order to be complete.

Feature: adding method to check for orders completed

---

src/core/engine/processors/kitchen_simulator.py
src/tests/core/engine/processors/kitchen_simulator_test.py

* Renaming methods inside kitchen simulator to:
* Process New orders
* Process orders in process

Refactor: Renaming process in the kitchen simulator

---

src/api/controllers/product_controller.py
src/constants/audit.py
src/lib/entities/abstract_entity.py
src/lib/entities/product.py
src/lib/repositories/generic_repository.py
src/lib/repositories/impl/product_repository_impl.py
src/tests/api/controllers/product_controller_integration_test.py
src/tests/api/controllers/product_controller_test.py
src/tests/lib/repositories/impl/product_repository_impl_test.py
src/tests/utils/fixtures/product_fixture.py

* adding audit structure to product repository

Feature: Adding audit structure to product repository and test

---

src/api/controllers/ingredient_controller.py
src/lib/entities/ingredient.py
src/lib/repositories/impl/ingredient_repository_impl.py
src/tests/api/controllers/ingredient_controller_integration_test.py
src/tests/api/controllers/ingredient_controller_test.py
src/tests/lib/repositories/impl/ingredient_repository_impl_test.py
src/tests/utils/fixtures/ingredient_fixture.py

* Adding audit structure to ingredient repository and test

Feature: Adding audit structure to ingredient repository and test

---

src/api/controllers/inventory_ingredient_controller.py
src/lib/entities/inventory_ingredient.py
src/lib/repositories/impl/inventory_ingredient_repository_impl.py
src/tests/api/controllers/inventory_ingredient_controller_integration_test.py
src/tests/api/controllers/inventory_ingredient_controller_test.py
src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py
src/tests/utils/fixtures/inventory_ingredient_fixture.py

* Adding audit structure to inventory ingredient repository and test

Feature: adding audit structure to inventory ingredient repository and test

---

src/api/controllers/inventory_controller.py
src/lib/entities/inventory.py
src/lib/repositories/impl/inventory_repository_impl.py
src/tests/api/controllers/inventory_controller_integration_test.py
src/tests/api/controllers/inventory_controller_test.py
src/tests/lib/repositories/impl/inventory_repository_impl_test.py
src/tests/utils/fixtures/inventory_fixture.py

* Adding audit structure to inventory repository and test

Feature: adding audit structure to inventory repository and test

---

src/api/controllers/chef_controller.py
src/lib/entities/chef.py
src/lib/repositories/impl/chef_repository_impl.py
src/tests/api/controllers/chef_controller_integration_test.py
src/tests/api/controllers/chef_controller_test.py
src/tests/lib/repositories/impl/chef_repository_impl_test.py
src/tests/utils/fixtures/chef_fixture.py

* Adding audit structure to chef repository and test

Feature: adding audit structure to chef repository and test

---

src/api/controllers/order_controller.py
src/lib/entities/order.py
src/lib/repositories/impl/order_repository_impl.py
src/tests/api/controllers/order_controller_integration_test.py
src/tests/api/controllers/order_controller_test.py
src/tests/lib/repositories/impl/order_repository_impl_test.py
src/tests/utils/fixtures/order_fixture.py

* Adding audit structure to order repository and test

Feature: adding audit structure to order repository and test

---

src/api/controllers/order_detail_controller.py
src/lib/entities/order_detail.py
src/lib/repositories/impl/order_detail_repository_impl.py
src/tests/api/controllers/order_detail_controller_integration_test.py
src/tests/api/controllers/order_detail_controller_test.py
src/tests/lib/repositories/impl/order_detail_repository_impl_test.py
src/tests/utils/fixtures/order_detail_fixture.py

* Adding audit structure to order detail repository and test

Feature: adding audit structure to order detail repository and test

---

src/api/controllers/order_status_history_controller.py
src/lib/entities/order_status_history.py
src/lib/repositories/impl/order_status_history_repository_impl.py
src/tests/api/controllers/order_status_history_controller_integration_test.py
src/tests/api/controllers/order_status_history_controller_test.py
src/tests/lib/repositories/impl/order_status_history_repository_impl_test.py
src/tests/utils/fixtures/order_status_history_fixture.py

* Adding audit structure to order status history repository and test

Feature: adding audit structure to order status history and test

---

src/core/engine/processors/kitchen_simulator.py
src/core/order_manager.py
src/tests/core/engine/processors/kitchen_simulator_integration_test.py
src/tests/core/order_manager_test.py

* Adding method to clean completed and cancelled queues after n values. the limit value is set by developer.

Feature: adding method to clean queues

---

src/core/engine/app_engine_processor.py
src/core/engine/processors/kitchen_simulator.py
src/seed/initial_data.py
src/tests/utils/fixtures/ingredient_fixture.py
src/tests/utils/fixtures/inventory_ingredient_fixture.py
src/tests/utils/fixtures/order_detail_fixture.py
src/tests/utils/fixtures/order_fixture.py
src/tests/utils/fixtures/product_fixture.py
src/tests/utils/fixtures/product_ingredient_fixture.py

* Refactoring initial data.
* creating 5 orders to test the kitchen simulator
* adding entity status and create by to all the entities
* Adding update by in the entity order at the kitchen simulator

Refactor: refactoring initial data

---

src/core/engine/processors/kitchen_simulator.py
src/lib/repositories/impl/order_repository_impl.py
src/tests/api/controllers/chef_controller_integration_test.py
src/tests/api/controllers/ingredient_controller_integration_test.py
src/tests/api/controllers/inventory_controller_integration_test.py
src/tests/api/controllers/inventory_ingredient_controller_integration_test.py
src/tests/api/controllers/order_controller_integration_test.py
src/tests/api/controllers/order_detail_controller_integration_test.py
src/tests/api/controllers/order_status_history_controller_integration_test.py
src/tests/api/controllers/product_controller_integration_test.py
src/tests/api/controllers/product_ingredient_controller_integration_test.py
src/tests/core/engine/processors/kitchen_simulator_integration_test.py
src/tests/lib/repositories/impl/chef_repository_impl_test.py
src/tests/lib/repositories/impl/ingredient_repository_impl_test.py
src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py
src/tests/lib/repositories/impl/inventory_repository_impl_test.py
src/tests/lib/repositories/impl/order_detail_repository_impl_test.py
src/tests/lib/repositories/impl/order_repository_impl_test.py
src/tests/lib/repositories/impl/order_status_history_repository_impl_test.py
src/tests/lib/repositories/impl/product_ingredient_repository_impl_test.py
src/tests/lib/repositories/impl/product_repository_impl_test.py

* Refactor kitchen simulator to let the assigned chef to orders complete
* fixing get available chefs implementation
* fixing get available chefs test
* deleting initial data method from kitchen simulator

Refactor: kitchen simulator

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

* Adding table and procedure script for users

Feature: Table and procedure for users

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

- adding table and procedure for product ingredients

Feature: Table and procedure for product_ingredients

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

* Adding table and procedure for ingredients

Feature: Table and procedure for ingredients

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

* Adding script for table and procedure of inventories

Feature: adding sql script for inventory

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

* Adding table and procedure for orders

Feature: adding sql script for order

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

* Adding table and procedure for order details

Feature: adding sql script for order details

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

* Adding table and procedure for order status history

Feature: adding sql script for order status histories

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

* Adding table and procedure for chefs

Feature: adding sql script for chefs

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

* Adding user roles 
* changing tables in procedures for insert into, wront tables.

Refactor: sql script

---

src/scripts/db_script.sql
src/scripts/fixtures_script.sql

* Adding constrains for relation between tables.
- fk_product_ingredient_ingredient
- fk_product_ingredient_product
- fk_inventory_ingredient_ingredient
- fk_inventory_ingredient_inventory
- fk_order_chef
- fk_order_detail_order
- fk_order_detail_product
- fk_order_status_history_order
- fk_chef_user
Note: 
* also renaming table that was written singular.
* adding some commas
* renaming some wronts variables
* adding some semicolons

Feature: sql script constraints

---

src/scripts/seeder.sql

* Adding initial data to create the data of the tables.

Feature: adding initial data to fill tables

---

README.md
requirements.txt
src/alembic.ini
src/migrations/env.py
src/migrations/script.py.mako
src/migrations/versions/c5d3236b81a3_db_script.py
src/scripts/db_script.sql

* Adding alembic toolkit for manage migrations with sqlalchemy
* Runnig firts migration to create db tables and constrains
* Adding Alembic and sqlalchemy versions to requirements.txt
* deleting comments from db_script
* Adding alembic commands to readme file

Feature: running first migration with alembic

---

src/migrations/versions/7dcd35c6f151_initial_data_script.py
src/migrations/versions/f094737d0027_procedures_script.py
src/scripts/fixtures_script.sql
src/scripts/seeder.sql

* Adding migrations for procedures and initial data(Seeder)

adding migrations for procedures and initial data

---

src/lib/entities/order.py

* mapping order class entity using sqlalchemy orm

feature : mapping order class entity

---

src/core/ioc.py
src/core/sqlalchemy_config.py
src/lib/entities/sqlalchemy_orm_mapping.py
src/lib/repositories/impl/inventory_repository_impl.py
src/lib/repositories_v2/chef_repository.py
src/lib/repositories_v2/impl/chef_repository_impl.py
src/tests/core/engine/processors/kitchen_simulator_test.py
src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py
src/tests/lib/repositories/impl/inventory_repository_impl_test.py
src/tests/lib/repositories/impl/order_repository_impl_test.py
src/tests/lib/repositories_v2/impl/chef_repository_impl_test.py
src/tests/lib/repositories_v2/sqlalchemy_base_repository_impl_test.py
src/tests/lib/repositories_v2/sqlalchemy_mock_builder.py
src/tests/utils/fixtures/mapping_orm_fixtures.py

* Mapping chef repository with sqlalchemy orm.

Feature: adding chef repository with orm

---

src/lib/repositories_v2/impl/product_repository_impl.py
src/lib/repositories_v2/product_repository.py
src/tests/lib/repositories_v2/impl/product_repository_impl_test.py
src/tests/utils/fixtures/mapping_orm_fixtures.py

* Adding product repository mapping with orm sqlalchemy

Feature : Adding product repository mapping with orm

---

src/lib/repositories_v2/impl/ingredient_repository_impl.py
src/tests/lib/repositories_v2/impl/ingredient_repository_impl_test.py
src/tests/utils/fixtures/mapping_orm_fixtures.py

* Adding ingredient repository mapping with orm
* Adding ingredient fixture to match orm
* Adding ingredient repository test

Feature: adding ingredient repository mapping with orm

---

src/lib/repositories_v2/impl/inventory_repository_impl.py
src/tests/lib/repositories_v2/impl/inventory_repository_impl_test.py
src/tests/utils/fixtures/mapping_orm_fixtures.py

* Adding inventory repository mapping with orm
* Adding inventory fixture to match with orm
* Adding inventory repository test

Feature: adding inventory repository mapping with orm

---

src/lib/repositories_v2/impl/order_detail_repository_impl.py
src/tests/lib/repositories_v2/impl/order_detail_repository_impl_test.py
src/tests/utils/fixtures/mapping_orm_fixtures.py

* Adding order detail mapping with orm
* Adding order detail fixture to match with orm
* Adding order detail repository test

Feature: adding order detail repository mapping with orm

---

src/lib/repositories_v2/impl/product_ingredient_repository_impl.py
src/lib/repositories_v2/product_ingredient_repository.py
src/tests/lib/repositories_v2/impl/product_ingredient_repository_impl.py
src/tests/utils/fixtures/mapping_orm_fixtures.py

* Adding product ingredient repository mapping with orm
* Adding product ingredient fixture to match orm
* Adding product ingredient repository test

adding product ingredient repository mapping with orm

---

src/lib/repositories_v2/impl/inventory_ingredient_repository_impl.py
src/lib/repositories_v2/inventory_ingredient_repository.py
src/tests/lib/repositories_v2/impl/inventory_ingredient_repository_impl_test.py
src/tests/lib/repositories_v2/sqlalchemy_mock_builder.py
src/tests/utils/fixtures/mapping_orm_fixtures.py
src/utils/inventory_ingredient_util.py

* Adding inventory ingredient repository mapping with orm
* Adding inventory ingredient fixture to match with orm
* Adding inventory ingredient repository test
* renaming varible ingredient quantity to quantity in inventory ingredient util

Feature: adding inventory ingredient repository mapping with orm

---

src/lib/repositories_v2/impl/order_status_history_repository_impl.py
src/lib/repositories_v2/order_status_history_repository.py
src/tests/lib/repositories_v2/impl/order_status_history_repository_impl_test.py
src/tests/utils/fixtures/mapping_orm_fixtures.py

* Adding order status history repository mapping with orm
* Adding order status history fixture to match with orm
* Adding order status history repository test

Feature: Adding order status history repository mapping with orm

---

src/lib/repositories_v2/impl/chef_repository_impl.py
src/tests/lib/repositories_v2/sqlalchemy_base_repository_impl_test.py

* Adding transactions validation to chef repository

Feature: adding transactions validation to chef repository

---

src/lib/repositories_v2/impl/ingredient_repository_impl.py
src/lib/repositories_v2/impl/inventory_ingredient_repository_impl.py
src/lib/repositories_v2/impl/inventory_repository_impl.py
src/lib/repositories_v2/impl/order_detail_repository_impl.py
src/lib/repositories_v2/impl/order_repository_impl.py
src/lib/repositories_v2/impl/order_status_history_repository_impl.py
src/lib/repositories_v2/impl/product_ingredient_repository_impl.py
src/lib/repositories_v2/impl/product_repository_impl.py

* adding transactions validation to repositories

Feature: adding transactions validation to repositories

---

src/core/ioc.py
src/lib/repositories/impl_v2/chef_repository_impl.py
src/tests/lib/repositories/impl_v2/chef_repository_impl_test.py

* modified ioc to use chef repository v2 instead of v1
* passing session to repository throught constructor

modified ioc to work with chef repository v2

---

src/core/ioc.py
src/lib/repositories/impl_v2/ingredient_repository_impl.py
src/lib/repositories/impl_v2/inventory_ingredient_repository_impl.py
src/lib/repositories/impl_v2/inventory_repository_impl.py
src/lib/repositories/impl_v2/order_detail_repository_impl.py
src/lib/repositories/impl_v2/order_repository_impl.py
src/lib/repositories/impl_v2/order_status_history_repository_impl.py
src/lib/repositories/impl_v2/product_ingredient_repository_impl.py
src/lib/repositories/impl_v2/product_repository_impl.py
src/tests/lib/repositories/impl_v2/ingredient_repository_impl_test.py
src/tests/lib/repositories/impl_v2/inventory_ingredient_repository_impl_test.py
src/tests/lib/repositories/impl_v2/inventory_repository_impl_test.py
src/tests/lib/repositories/impl_v2/order_detail_repository_impl_test.py
src/tests/lib/repositories/impl_v2/order_repository_impl_test.py
src/tests/lib/repositories/impl_v2/order_status_history_repository_impl_test.py
src/tests/lib/repositories/impl_v2/product_ingredient_repository_impl.py
src/tests/lib/repositories/impl_v2/product_repository_impl_test.py

* Modified ioc to work with repositories v2

Refactor: refactoring ioc to work with repositories v2

---

src/tests/api/controllers/chef_controller_integration_test_v2.py
src/tests/api/controllers/ingredient_controller_integration_test_v2.py
src/tests/api/controllers/inventory_controller_integration_test_v2.py
src/tests/api/controllers/inventory_ingredient_controller_test_v2.py
src/tests/api/controllers/order_controller_integration_test_v2.py
src/tests/api/controllers/order_detail_controller_integration_test_v2.py
src/tests/api/controllers/order_status_history_controller_test_v2.py
src/tests/api/controllers/product_controller_integration_test_v2.py
src/tests/api/controllers/product_ingredient_controller_integration_test_v2.py
src/tests/core/engine/processors/kichen_simulator_integration_test_v2.py

* Adding integration test v2 for controllers
* Adding integration test v2 for kitchen simulator

adding version 2 of integration test

---

alembic.ini
requirements.txt
src/migrations/versions/da1fd865c698_updating_order_status_histories_table.py

* Adding migration to update order status history table
update:
* Adding column mongo_order_status_history_uuid
* truncate table to delete data table.

adding migration to update order status history table

---

requirements.txt
src/core/ioc.py
src/core/mongo_engine_config.py
src/lib/entities/mongo_engine_odm_mapping.py
src/lib/repositories/impl_no_sql/order_status_history_repository_impl.py
src/tests/lib/repositories/impl_no_sql/order_status_history_impl_test.py
src/tests/lib/repositories/mongo_engine_base_repository_impl_test.py
src/tests/utils/fixtures/mapping_odm_fixtures.py

* Adding order status history repository mapping with ODM MongoEngine
* Adding Order Status History entity mapping with ODM MongoEngine
* Adding conection config
* Adding Order status History fixture mapping with ODM MongoEngine
* Adding order status history repository test

Feature: adding order status history repository with mongo

---

src/constants/etl_status.py
src/lib/entities/mongo_engine_odm_mapping.py
src/lib/entities/sqlalchemy_orm_mapping.py
src/migrations/versions/1742179fdeb5_adding_etl_status_to_order_status_.py

* Adding etl status to postgresql order status history table
* Adding etl status to order status history odm
* Adding enum to manage etl status

Feature: adding migration to add etl status to postgresql and mongo

---

src/api/controllers/order_status_history_controller.py
src/lib/repositories/impl_v2/order_status_history_repository_impl.py
src/tests/lib/repositories/impl_v2/order_status_history_repository_impl_test.py

* Adding method in order status history repository v2 to update etl status in posgresql.

Feature: adding method to update etl status in postgres table

---

src/core/engine/processors/kitchen_simulator.py
src/core/ioc.py
src/tests/core/engine/processors/kichen_simulator_integration_test_v2.py
src/tests/core/engine/processors/kitchen_simulator_integration_test.py
src/tests/core/engine/processors/kitchen_simulator_test.py

* Refactoring Ioc to have mongo and postgresql repositories and controllers
* refactoring kitchen simulator to point to mongo and postgresql controllers
* refactoring kitchen simultator test to point to mongo and postgresql controllers

Refactor: refactoring ioc to have postgres and mongo controllers and repositories

---

src/api/controllers/order_status_history_controller.py
src/constants/audit.py
src/core/engine/app_engine_processor.py
src/core/engine/processors/abstract_etl_processor.py
src/core/engine/processors/mongo_to_postgresql_order_status_history.py
src/lib/entities/sqlalchemy_orm_mapping.py
src/lib/repositories/impl_no_sql/order_status_history_repository_impl.py
src/lib/repositories/impl_v2/order_status_history_repository_impl.py
src/tests/core/engine/processors/abstract_etl_processor_test.py
src/tests/core/engine/processors/mongo_to_postgres_order_status_history_integration_test.py
src/tests/core/engine/processors/mongo_to_postgres_order_status_history_test.py
src/tests/lib/repositories/impl_no_sql/order_status_history_impl_test.py
src/tests/utils/etl_util_test.py
src/utils/etl_util.py

* Adding first ETL to load data from mongo db into postgresql table.
* Adding first ETL to load data from postgresql to mongo documents

Feature: Adding first etl to load mongo data into postgresql

---

src/lib/entities/chef.py
src/lib/entities/inventory_ingredient.py
src/lib/repositories/impl/chef_repository_impl.py
src/lib/repositories/impl/inventory_ingredient_repository_impl.py
src/lib/repositories/impl/order_repository_impl.py
src/lib/repositories/impl/product_ingredient_repository_impl.py
src/tests/api/controllers/chef_controller_integration_test.py
src/tests/api/controllers/inventory_ingredient_controller_integration_test.py
src/tests/api/controllers/order_controller_integration_test.py
src/tests/core/engine/app_engine_processor_integration_test.py
src/tests/core/engine/app_engine_processor_test.py
src/tests/core/engine/processors/kitchen_simulator_integration_test.py
src/tests/lib/repositories/impl/chef_repository_impl_test.py
src/tests/lib/repositories/impl/inventory_ingredient_repository_impl_test.py
src/tests/lib/repositories/impl/order_repository_impl_test.py
src/tests/lib/repositories/impl_v2/order_status_history_repository_impl_test.py
src/tests/utils/fixtures/chef_fixture.py
src/tests/utils/fixtures/inventory_ingredient_fixture.py
src/tests/utils/inventory_ingredient_util_test.py

* Refactoring some test. 
* Replacing ingredient_quantity for quantity.
* Replacing chef_skills for skill
* Replacing ingredient_type for cooking_tipe
* skippen 5 deprecated test methods

Refactor: Fixing some test inconsistencies

---

.pre-commit-config.yaml
src/tests/core/engine/processors/mongo_to_postgres_order_status_history_test.py

* fixing pre commit test config
*  removing unused imports

fixing pre commit test config

---

src/api/controllers/order_status_history_controller.py
src/core/engine/processors/mongo_to_postgresql_order_status_history.py
src/lib/repositories/impl_no_sql/order_status_history_repository_impl.py
src/lib/repositories/impl_v2/order_status_history_repository_impl.py
src/lib/repositories/order_status_history_repository.py
src/tests/lib/repositories/impl_no_sql/order_status_history_impl_test.py

* Adding method to get unprocessed order status histories
* Adding test for method get unprocessed order status histories
* modify etl mongo to postgresql to use method get unprocessed order status histories

Feature: adding method to get unprocessed order status histories

---

README.md
src/api/controllers/chef_controller.py
src/constants/audit.py
src/core/engine/processors/kitchen_simulator.py
src/env_config.py
src/flask/api_setup.py
src/flask/routes/chef.py
src/flask/run_flask_app.py
src/flask/schemas/chef_schema.py
src/flask/utils/api_util.py
src/lib/repositories/impl_v2/chef_repository_impl.py
src/tests/core/dependency_injection_test.py
src/tests/core/engine/processors/abstract_etl_processor_test.py
src/tests/core/engine/processors/abstract_processor_test.py
src/tests/core/engine/processors/kichen_simulator_integration_test_v2.py
src/tests/core/engine/processors/kitchen_simulator_test.py
src/tests/core/engine/processors/mongo_to_postgres_order_status_history_integration_test.py
src/tests/core/order_manager_test.py
src/tests/e2e/api/chef_api_e2e_test.py
src/tests/e2e/base_flask_setup_test.py
src/tests/e2e/utils/api_util_test.py
src/tests/lib/repositories/impl_v2/chef_repository_impl_test.py
src/tests/lib/repositories/mongo_engine_base_repository_impl_test.py
src/tests/lib/repositories/sqlalchemy_base_repository_impl_test.py
src/tests/utils/fixtures/json_entities_fixture.py
src/tests/utils/fixtures/mapping_orm_fixtures.py

* Adding chef endpoints to access chef controller from navigator

creating chef endpoints

---

src/api/controllers/inventory_controller.py
src/api/controllers/inventory_ingredient_controller.py
src/constants/http_status_code.py
src/flask/api_setup.py
src/flask/routes/chef.py
src/flask/routes/ingredient.py
src/flask/routes/inventory.py
src/flask/routes/inventory_ingredient.py
src/flask/schemas/inventory_ingredient_schema.py
src/flask/schemas/inventory_schema.py
src/lib/repositories/impl_v2/inventory_ingredient_repository_impl.py
src/lib/repositories/impl_v2/inventory_repository_impl.py
src/tests/e2e/api/chef_api_e2e_test.py
src/tests/e2e/api/ingredient_api_e2e_test.py
src/tests/e2e/api/inventory_api_e2e_test.py
src/tests/e2e/api/inventory_ingredient_api_e2e_test.py
src/tests/utils/fixtures/json_entities_fixture.py

* adding endpoints for inventory ingredient controller
* adding e2e test for inventory ingredient controller endpoints

Feature: creating inventory ingredient endpoints

---

src/api/controllers/order_detail_controller.py
src/flask/api_setup.py
src/flask/routes/order_detail.py
src/flask/schemas/order_detail_schema.py
src/lib/repositories/impl_v2/order_detail_repository_impl.py
src/tests/e2e/api/order_detail_api_e2e_test.py
src/tests/utils/fixtures/json_entities_fixture.py

* adding endpoints for order detail controller
* adding e2e test for order detail controller endpoitns

Feature: creating order detail endpoints

---

src/api/controllers/order_controller.py
src/flask/api_setup.py
src/flask/routes/order.py
src/flask/schemas/order_schema.py
src/flask/schemas/product_ingredient_schema.py
src/lib/repositories/impl_v2/order_repository_impl.py
src/tests/e2e/api/order_api_e2e_test.py
src/tests/utils/fixtures/json_entities_fixture.py
src/tests/utils/fixtures/mapping_orm_fixtures.py

* Adding endpoints for order controller
* Adding e2e test for order controller endpoints

Feature: creating order endpoints

---

src/api/controllers/product_controller.py
src/flask/api_setup.py
src/flask/routes/product.py
src/flask/schemas/product_schema.py
src/lib/repositories/impl_v2/product_repository_impl.py
src/tests/e2e/api/product_api_e2e_test.py
src/tests/utils/fixtures/json_entities_fixture.py

* Adding product controller endpoints
* Adding e2e test for product controller endpoints

Feature: creating product endpoints

---

src/api/controllers/order_status_history_controller.py
src/flask/api_setup.py
src/flask/routes/order_status_history.py
src/flask/schemas/order_status_history_schema.py
src/lib/repositories/impl_v2/order_status_history_repository_impl.py
src/tests/e2e/api/order_status_history_api_e2e_test.py
src/tests/utils/fixtures/json_entities_fixture.py

* Adding order status history controller endpoints
* Adding e2e test for order status history controller endpoints

Feature: creating order status history endpoints

---

src/migrations/versions/3b2f675ecb1d_oauth_tables_initial_data.py
src/migrations/versions/a7934568d9f0_oauth_tables_script.py
src/scripts/oauth_tables_initial_data.sql
src/scripts/oauth_tables_script.sql

* altering user table to set user_name as unique
* creating app_clients table
* creating app_scopes table
* creating app_client_users table
* creating app_access_tokens table
* creating app_refresh_tokens table
* adding constrains for relationship between tables.

Feature: adding migration to create table user authentication

---

src/lib/entities/sqlalchemy_orm_mapping.py
src/lib/repositories/impl_oauth2/oauth2_repository_impl.py
src/migrations/versions/c26049706f23_renaming_user_name_to_username_in_whole_.py
src/utils/sql_oath2_queries.py

* Renaming user_name to username in whole project
* Creating migration to rename user_name to username in database.

Refactor: Renaming user_name to username in whole project

---

src/core/di_config.py
src/lib/repositories/impl_v2/oauth2_repository_impl.py
src/tests/lib/repositories/impl_v2/oauth2_repository_impl_test.py
src/tests/utils/fixtures/oauth2_fixture.py
src/utils/oauth2_util.py

* Adding test for oauth2 repository
* Creating fixture to test oauth2 repository
* Moving oauth2 repository to impl_v2 folder

feature/ adding test to oauth2 repository

---

src/constants/http.py
src/constants/http_status_code.py
src/constants/oauth2.py
src/exceptions/exceptions.py
src/flask/api_setup.py
src/flask/routes/chef.py
src/flask/routes/ingredient.py
src/flask/routes/inventory.py
src/flask/routes/inventory_ingredient.py
src/flask/routes/order.py
src/flask/routes/order_detail.py
src/flask/routes/order_status_history.py
src/flask/routes/product.py
src/flask/routes/product_ingredient.py
src/flask/routes/security_route_middleware.py
src/lib/entities/secured_http_request_Url_permissions.py
src/lib/entities/secured_http_request_uri.py
src/lib/repositories/impl_v2/oauth2_repository_impl.py
src/tests/e2e/api/chef_api_e2e_test.py
src/tests/flask/before_request_middleware_function.py
src/tests/flask/flask__base_endpoint_function_test.py
src/tests/flask/security_route_middleware_integration_test.py
src/tests/flask/security_route_middleware_test.py
src/tests/lib/repositories/impl_v2/oauth2_repository_impl_test.py
src/tests/utils/fixtures/endpoint_request_fixture.py
src/tests/utils/fixtures/oauth2_fixture.py
src/tests/utils/fixtures/token_fixture.py
src/tests/utils/oauth2_util_test.py
src/utils/oauth2_util.py

Adding middleware using flask `before app request` to validate access_token and validate if user/client have the
authorization to access to an specific endpoint.

Feature: adding middleware to endpoint access validation

---

src/tests/e2e/api/chef_api_e2e_test.py
src/tests/e2e/api/ingredient_api_e2e_test.py
src/utils/oauth2_util.py

* Adding roles and scopes for ingredient endpoints
* fixing ingredient e2e test. adding acces token to test protected endpoints

Feature: protecting ingredient endpoints

---

src/tests/e2e/api/inventory_api_e2e_test.py
src/utils/oauth2_util.py

* Protecting inventory endpoints
* Fixing inventory e2e test.

Feature: protecting inventory endpoints

---

src/tests/e2e/api/inventory_ingredient_api_e2e_test.py
src/utils/oauth2_util.py

* Protecting inventory ingredient endpoints
* fixing inventory ingredient e2e test.

Feature: Protecting inventory ingredient endpoints

---

src/tests/e2e/api/order_api_e2e_test.py
src/utils/oauth2_util.py

* Protecting order endpoints
* fixing order e2e test.

Feature: protecting order endpoints

---

src/tests/e2e/api/order_detail_api_e2e_test.py
src/utils/oauth2_util.py

* Protecting order detail endpoints
* Fixing order details e2e test.

Feature: protecting order detail endpoints

---

src/tests/e2e/api/order_status_history_api_e2e_test.py
src/utils/oauth2_util.py

* Protecting order status history endpoints
* Fixing order status history  e2e test

feature: Protecting order status history endpoints

---

src/tests/e2e/api/product_ingredient_api_e2e_test.py
src/utils/oauth2_util.py

* protecting product ingredient endpoints
* Fixing product ingredients e2e test

Feature: Protecting product ingredient endpoints

---

src/exceptions/exceptions.py
src/lib/repositories/impl_v2/oauth2_repository_impl.py
src/tests/lib/repositories/impl_v2/oauth2_repository_impl_test.py

* Refactor to rollback changes made in last PR about validate client/user.

Refactor:  Rollback client/user validate wrong credentials

---

src/flask/api_setup.py
src/flask/routes/oauth2.py
src/lib/repositories/impl_v2/oauth2_repository_impl.py
src/tests/e2e/api/oauth2_api_e2e_test.py
src/tests/e2e/base_flask_setup_test.py
src/tests/utils/fixtures/mapping_orm_fixtures.py
src/tests/utils/fixtures/oauth2_fixture.py
src/tests/utils/fixtures/token_fixture.py
src/tests/utils/oauth2_util_test.py
src/utils/oauth2_util.py
src/utils/time_util.py

* Adding oauth2 login endpoint

Feature: adding oauth2 login endpoint

---

src/flask/routes/oauth2.py
src/flask/routes/security_route_middleware.py
src/lib/repositories/impl_v2/oauth2_repository_impl.py
src/tests/e2e/api/oauth2_api_e2e_test.py
src/tests/lib/repositories/impl_v2/oauth2_repository_impl_test.py
src/tests/utils/fixtures/endpoint_request_fixture.py
src/tests/utils/fixtures/mapping_orm_fixtures.py
src/utils/oauth2_util.py
src/utils/sql_oath2_queries.py

* Adding endpoint for refresh token

Feature: Oauth2 refresh token endpoint

---

src/flask/routes/oauth2.py
src/tests/e2e/api/oauth2_api_e2e_test.py
src/tests/utils/fixtures/endpoint_request_fixture.py
src/tests/utils/fixtures/oauth2_fixture.py
src/tests/utils/oauth2_util_test.py
src/utils/oauth2_util.py

* Encrypting client credentials
* fixing ouaht2 e2e test
* adding unit test for decrypt_client_credentials util

encrypting client credentials

---

src/lib/repositories/impl_v2/oauth2_repository_impl.py
src/tests/lib/repositories/impl_v2/oauth2_repository_impl_test.py
src/utils/sql_oath2_queries.py

* Adding validation by client id and user active for refresh token

Feature: adding client and user validation for refresh token

---

src/migrations/versions/416bd51c24e5_refactoring_bd_username_and_roles.py

* renaming column `role` to `roles` in users table
* renaming variable `user_name` to `username` in users procedure
* adding `ADMINISTRATOR` to `user_role_enum`
* encrpting password to user id 3. This user is use to test the project.
* updating scope `READ/WRITE` to `READ` as the scope `READ/WRITE` doesn't exist

Refactor: adding migration to refactor username and roles in bd

---

src/lib/entities/sqlalchemy_orm_mapping.py
src/migrations/versions/809dd14b4b64_bd_enums_to_varchar.py
src/tests/lib/repositories/impl_v2/oauth2_repository_impl_test.py
src/tests/utils/oauth2_util_test.py

* Changing entity status column from enum to varchar
* Changing cooking type column from enum to varchar
* Changing status type column from enum to varchar
* Changing scope type column from enum to varchar
* Changing roles type column from enum to varchar
* Changing user_type type column from enum to varchar
* Changing from_status/to_status type column from enum to varchar

Refactor: refactoring enum to varchar in Bd

---

README.md
requirements.txt

* Reactoring `README` file to clarify steps to setup project.
* Removing jwt dependency from requirements.txt

Refactor: refactoring Readme file

---

src/constants/etl_status.py
src/lib/entities/mongo_engine_odm_mapping.py
src/lib/repositories/impl_no_sql/order_status_history_repository_impl.py
src/lib/repositories/impl_v2/order_status_history_repository_impl.py
src/lib/repositories/order_status_history_repository.py
src/tests/lib/repositories/impl_no_sql/order_status_history_impl_test.py

* Adding method `get_mongo_order_status_histories_by_service`
* Adding method `update_batch_to_assigned_etl`
* Adding service constant to etl status
* Adding test for these methods

Feature: adding methods to mongo repository to use in mongo order status distribution

---

src/migrations/versions/8dda351079cc_adding_python_app_client.py

* Adding migration to add python client to `app_clients` table

adding migration to add python client to app_clients table

---

src/utils/grpc_util.py
src/utils/time_util.py

* refactoring time util to avoid `none` datetime and converting time unix to `int`

refactor time and grpc util

---

src/lib/repositories/impl_no_sql/order_status_history_repository_impl.py

* adding created date and updated date to new order status histories.

Refactor: order status history repository
